### ISSUE TITLE
May I get some credit in the app?

### ISSUE THREAD

**Issue by fr3fou** [OctoDumb/osu-speed#3]
Hi!

Nice app you've got there, I saw the README.md and was glad to see my name there, thanks :D. But would it be possible to also add my name in the app as well?

**Comment by uzervlad** [comment]
Of course, we'll add it in the next update!

**Comment by uzervlad** [comment]
Done b2ce4c6ffb6aa97c7250617763a0ed355ad4b48b

**Comment by fr3fou** [comment]
Thanks!
